### ISSUE TITLE
Decide that to do with autocomplete plugin

### ISSUE THREAD

**Issue by juho-jaakkola** [juho-jaakkola/elgg-event_calendar#25]
Autocomplete plugin currently overrides the Elgg core input/autocomplete view, so best approach might be to get rid of it completely.

**Comment by juho-jaakkola** [comment]
@iionly Which plugin is this? I didn't find it from the repositories of @kevinjardine

**Comment by juho-jaakkola** [comment]
I didn't in fact even find any references to the plugin in the source.

**Comment by iionly** [comment]
Kevin has no repo of his autocomplete plugin but only made it available on the community site.

I have created a repo at https://github.com/iionly/autocomplete.

Event Calendar uses the function autocomplete_member_to_user() in model.php that is provided by the autocomplete plugin.

**Comment by iionly** [comment]
If the Elgg core autocomplete can replace the custom autocomplete of this plugin without issues, I'm all in for dropping the dependency on this autocomplete plugin (like dropping the dependency on the userpicker_plus plugin). My guess is that Kevin wrote these plugins at a time when the core autocomplete and userpicker might not have provided all the functionality needed yet. As the autocomplete and userpicker_plus plugin seem almost not used by event_calendar I don't think there's much loss if they would no longer be used (or necessary).

**Comment by juho-jaakkola** [comment]
This is weird. The autocomplete plugin is used only in the event save action.

If the plugin is enabled, it attempts to get input with name 'adduser'. There however isn't any input field like that in any of the plugins (event_calendar, autocomplete, userpicker_plus).

**Comment by juho-jaakkola** [comment]
Yep, the feature is obsolete: https://github.com/kevinjardine/Elgg-Event-Calendar/blob/a77da8ad31087cbe41767080c5dd0c71a25d879c/views/default/forms/event_calendar/edit.php#L166-L173
