### ISSUE TITLE
Decide what to do with message_queue plugin

### ISSUE THREAD

**Issue by juho-jaakkola** [juho-jaakkola/elgg-event_calendar#26]
https://github.com/kevinjardine/message_queue

The message_queue plugin works differently than I thought at first. It doesn't queue up notifications like Elgg core (1.9+) does to send them almost immediately. Instead the messages are rather reminders to be sent at a pre-defined time before an event.

So it might make sense to keep the plugin separate (as it might be of use for other plugins, too). It's only necessary to test that it works fine.

**Comment by juho-jaakkola** [comment]
Disabling/removing the message_queue plugin doesn't break anything. So I believe the dependency can be left as it is.

**Comment by iionly** [comment]
Maybe adding it at least as "suggests" in manifest.xml.

Updated repo is at https://github.com/iionly/message_queue. I've not fully tested it though (on Elgg 1.8). I would also do the upgrading to Elgg 1.9/1.10 if necessary and deal with making a new release at the community site.
