### ISSUE TITLE
"Open events" tab working or not?

### ISSUE THREAD

**Issue by iionly** [juho-jaakkola/elgg-event_calendar#32]
Either I don't understand what the "open events" tabs is supposed to provide or it might not work at all. As I understand it, the "open events" tab should list the events with open spots (the tab gets displayed only when the spots plugin option is enabled). But I don't get any events listed on this tab at all.

Sidenote: even if the "open events" tab would work as intended I don't like it to be the default tab. Does this really make any sense? I would prefer the "All" tab to be the default tab ("All" tab due to changes in language file not yet provided as PR).

**Comment by juho-jaakkola** [comment]
Did the new tab appear when you upgraded the fullcalendar plugin?

I wonder why the tab is not displayed in the 1.9 branch.

**Comment by iionly** [comment]
I've not tried it on Elgg 1.9 yet so I don't know if there were changes resulting in this tab not to show up.

But it has nothing to do with fullcalendar. There is a plugin setting to enable a "spots" input field (= limited number of people who can attend to an event). Only with this setting enabled the tab is displayed (as this tab filters the events that are not yet full). But the tab never shows any entries for me.

**Comment by iionly** [comment]
I think I was able to fix this issue (still some more testing necessary to be sure).

Problem was that number of spots of an event / number of free spots are handled by creation of relationships ("personal_event") between event entity and user entity but for the listing of open events (i.e. events were number of relationships is <= number of spots) there was made a query looking for annotations named "personal_event"...
