### ISSUE TITLE
Text collision with right border in datepicker input and jquery calendar display

### ISSUE THREAD

**Issue by iionly** [juho-jaakkola/elgg-event_calendar#49]
Elgg 1.9 (and newer) only. It might only occur with Aalborg theme due to the larger font. But the outermost right column is partyl hidden below the right border both in input and output. Input is a problem when selecting the date on new events, output is a problem is the list views that display the calendar (with exception of fullcalendar lists).

**Comment by iionly** [comment]
Reference: https://github.com/Elgg/Elgg/issues/7542

**Comment by iionly** [comment]
The underlying issue with datepicker was fixed in Elgg 1.10. So, this problem with the datepicker within Event Calendar also occurs only on Elgg 1.9 but no longer on Elgg 1.10. So, it might be a "won't fix" issue. What do you think, @juho-jaakkola ?

P.S.: It seems there are still some adjustments necessary to account for the larger font, e.g. in list views. I'll deal with that separately in the next few days (not opening an issue about it for now).

**Comment by juho-jaakkola** [comment]
Yes, I'd say wontfix.
