### ISSUE TITLE
Site notification on receiving an event request has no link to corresponding manage page

### ISSUE THREAD

**Issue by iionly** [juho-jaakkola/elgg-event_calendar#50]
The new notification system seems to work regarding sending a site notification to the event owner on receiving a request for the event to be added to a user's personal calendar.

But the notification is not linking to the corresponding event page or even better directly to the manage page of this event to directly deal with the request. The notification text (or subject... not sure at the moment) should be made a link for convenience.

**Comment by juho-jaakkola** [comment]
We need to pass more details into `notify_user()` as the 5th parameter. An example: https://github.com/Elgg/Elgg/blob/1.9/actions/comment/save.php#L75

I'm not yet completely sure what exactly should be passed into it. The `object` parameter should be the entity being acted upon. The link however doesn't take user to an entity, but to a list of requests.

**Comment by juho-jaakkola** [comment]
One option would be to pass the relationship as the object, and use the `'prepare', 'notification:create:relationship:event_calendar_request'` hook to add a custom link. This however seems a bit bloated.

(It may even be that the notifications system throws an exception because it doesn't officially support relationships yet. I don't remember ATM.)

**Comment by iionly** [comment]
As far as I remember this issue on the Elgg repo the notification system might not support relationships. I think the issue was that annotations failed to work and it turned out that it worked only for entities.

I have to look into the different possibilites some more to be able to judge them.

**Comment by iionly** [comment]
Using the 5th parameter of notify_user() seems a working solution. I've tested it for the notifications of event subscriptions and it seems to work:

``` php
notify_user($user_guid, $site_guid, $subject, $message, array(
    'object' => $event,
    'action' => 'subscribe',
    'summary' => $subject
));
```

I've used 'subscribe' as action without much of an idea of where it's actually used. Could it be a problem?

I have to check the other usages of notify_user() within event calendar before I can be sure if it works for them all. Especially in one case the 5th parameter is already in use but not with an associative array (I guess this was introduced in Elgg only after it was already in use in event calendar).

In one case the usage of notify_user() might be problematic: there's a plugin setting to automatically add a group event to the personal calendars of all group members. I need to check if this triggers also sending of notifications. If yes, this could be problematic and in this case the new notification system might be the better choice after all (if it's possible to be used).

**Comment by juho-jaakkola** [comment]
Have you already finished some code for this?

> I've used 'subscribe' as action without much of an idea of where it's actually used. Could it be a problem?

`notify_user()`doesn't currently trigger any hooks where it is used. So no problem.

> Especially in one case the 5th parameter is already in use but not with an associative array (I guess this was introduced in Elgg only after it was already in use in event calendar).

The parameter existed pre-1.9. It just wasn't really used for anything by core until 1.9. If you mean the `null` parameter, that won't cause problems, and can be replaced by the parameter array.

> there's a plugin setting to automatically add a group event to the personal calendars of all group members. I need to check if this triggers also sending of notifications.

No, it is not sending notifications. It just adds the relationship: https://github.com/juho-jaakkola/elgg-event_calendar/blob/1.9/models/model.php#L883

**Comment by iionly** [comment]
As I mentioned in my PM I've made a separate repo where I merged my code including the PR to fix the notification issue (https://github.com/iionly/event_calendar/commit/9482196ddc1cc887a5c811a81319277dc09f179f).

**Comment by juho-jaakkola** [comment]
Feel free to make a PR.

Two notes:
- I the action names for notify_user() do not need to be that long because they're already associated to an event
- Logged in used doesn't necessarily use same language as the recipient, so you should pass recipient language into elgg_echo()

**Comment by iionly** [comment]
The action name might be longer than necessary. But better a descriptive name than a cryptic name.
