### ISSUE TITLE
The option "Automatically add group events for all members to their personal calendars" it's broken

### ISSUE THREAD

**Issue by Yaco** [juho-jaakkola/elgg-event_calendar#57]
If I enable the option "Automatically add group events for all members to their personal calendars" in the admin panel, and then create an event, I get the following error:

```
Fatal error: Call to a member function getMembers() on a non-object in [...]/event_calendar/models/model.php on line 893
```

**Comment by iionly** [comment]
Got broken on updating the event calendar code for Elgg 1.9. Easy to fix. I'll wait with submitting a PR for the currently open PRs to be merged first (@juho-jaakkola).
