### ISSUE TITLE
Can we assume this plugin is dead?

### ISSUE THREAD

**Issue by Kikketer** [juho-jaakkola/elgg-event_calendar#75]
Elgg had an update 11 days ago, this plugin is 7 years old.  Is there an alternative plugin that you may suggest?

**Comment by iionly** [comment]
This fork here is probably dead.

I'd updated the original version some years ago to be useable up to Elgg 2.3 (https://github.com/iionly/event_calendar) but I had no time during the last few years to also update it further for Elgg 3 (and Elgg 4 what I assume you are interested in). My version is not dead but taking a long nap for sure (I had started to work on it again a couple of months ago but had to take a break that is hopefully soon over). Another fork that is supposed to work for Elgg 3 is available at https://github.com/Ngseri/event_calendar but I had found a few issues with (maybe minor) functionality not working so I'll work on a Elgg 3 and then Elgg 3 version on my own.

If you need an Elgg plugin to be able to handle event stuff right now for Elgg 3 and Elgg 4 you might want to try the Event Manager plugin (https://elgg.org/plugins/736695). It should offer the same functionality also offered by the Event Calendar plugin (maybe even more by now). But there's no option I know of to switch from one plugin to the other at a later time so you would have to stick with what you've chosen.

**Comment by Kikketer** [comment]
Ok thanks, I have the Event Manager plugin in and running right now.  Was hoping to add a calendar type widget that shows these events on the front page.  I'm still hacking around in here to try and figure that out, I thought this plugin was a step closer to that.

**Comment by juho-jaakkola** [comment]
Yeah, I'm unfortunately not maintaining this fork of the plugin anymore.
